/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CompetitorsChangesRouteImport } from './routes/competitors.changes'
import { Route as CompetitorsCompaniesRouteImport } from './routes/competitors.companies'
import { Route as CompetitorsInitiativesRouteImport } from './routes/competitors.initiatives'
import { Route as CompetitorsOverviewRouteImport } from './routes/competitors.overview'
import { Route as CompetitorsTargetsRouteImport } from './routes/competitors.targets'
import { Route as CompetitorsCompaniesCompanyIdRouteImport } from './routes/competitors.companies.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsChangesRoute = CompetitorsChangesRouteImport.update({
  id: '/competitors/changes',
  path: '/competitors/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsCompaniesRoute = CompetitorsCompaniesRouteImport.update({
  id: '/competitors/companies',
  path: '/competitors/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsInitiativesRoute = CompetitorsInitiativesRouteImport.update({
  id: '/competitors/initiatives',
  path: '/competitors/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsOverviewRoute = CompetitorsOverviewRouteImport.update({
  id: '/competitors/overview',
  path: '/competitors/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsTargetsRoute = CompetitorsTargetsRouteImport.update({
  id: '/competitors/targets',
  path: '/competitors/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsCompaniesCompanyIdRoute =
  CompetitorsCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => CompetitorsCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/competitors/changes': typeof CompetitorsChangesRoute
  '/competitors/companies': typeof CompetitorsCompaniesRouteWithChildren
  '/competitors/initiatives': typeof CompetitorsInitiativesRoute
  '/competitors/overview': typeof CompetitorsOverviewRoute
  '/competitors/targets': typeof CompetitorsTargetsRoute
  '/competitors/companies/$companyId': typeof CompetitorsCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/competitors/changes': typeof CompetitorsChangesRoute
  '/competitors/companies': typeof CompetitorsCompaniesRouteWithChildren
  '/competitors/initiatives': typeof CompetitorsInitiativesRoute
  '/competitors/overview': typeof CompetitorsOverviewRoute
  '/competitors/targets': typeof CompetitorsTargetsRoute
  '/competitors/companies/$companyId': typeof CompetitorsCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/competitors/changes': typeof CompetitorsChangesRoute
  '/competitors/companies': typeof CompetitorsCompaniesRouteWithChildren
  '/competitors/initiatives': typeof CompetitorsInitiativesRoute
  '/competitors/overview': typeof CompetitorsOverviewRoute
  '/competitors/targets': typeof CompetitorsTargetsRoute
  '/competitors/companies/$companyId': typeof CompetitorsCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/search'
    | '/article/$id'
    | '/category/$slug'
    | '/competitors/changes'
    | '/competitors/companies'
    | '/competitors/initiatives'
    | '/competitors/overview'
    | '/competitors/targets'
    | '/competitors/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/search'
    | '/article/$id'
    | '/category/$slug'
    | '/competitors/changes'
    | '/competitors/companies'
    | '/competitors/initiatives'
    | '/competitors/overview'
    | '/competitors/targets'
    | '/competitors/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/search'
    | '/article/$id'
    | '/category/$slug'
    | '/competitors/changes'
    | '/competitors/companies'
    | '/competitors/initiatives'
    | '/competitors/overview'
    | '/competitors/targets'
    | '/competitors/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  SearchRoute: typeof SearchRoute
  ArticleIdRoute: typeof ArticleIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CompetitorsChangesRoute: typeof CompetitorsChangesRoute
  CompetitorsCompaniesRoute: typeof CompetitorsCompaniesRouteWithChildren
  CompetitorsInitiativesRoute: typeof CompetitorsInitiativesRoute
  CompetitorsOverviewRoute: typeof CompetitorsOverviewRoute
  CompetitorsTargetsRoute: typeof CompetitorsTargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/changes': {
      id: '/competitors/changes'
      path: '/competitors/changes'
      fullPath: '/competitors/changes'
      preLoaderRoute: typeof CompetitorsChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/companies': {
      id: '/competitors/companies'
      path: '/competitors/companies'
      fullPath: '/competitors/companies'
      preLoaderRoute: typeof CompetitorsCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/initiatives': {
      id: '/competitors/initiatives'
      path: '/competitors/initiatives'
      fullPath: '/competitors/initiatives'
      preLoaderRoute: typeof CompetitorsInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/overview': {
      id: '/competitors/overview'
      path: '/competitors/overview'
      fullPath: '/competitors/overview'
      preLoaderRoute: typeof CompetitorsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/targets': {
      id: '/competitors/targets'
      path: '/competitors/targets'
      fullPath: '/competitors/targets'
      preLoaderRoute: typeof CompetitorsTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/companies/$companyId': {
      id: '/competitors/companies/$companyId'
      path: '/$companyId'
      fullPath: '/competitors/companies/$companyId'
      preLoaderRoute: typeof CompetitorsCompaniesCompanyIdRouteImport
      parentRoute: typeof CompetitorsCompaniesRoute
    }
  }
}

interface CompetitorsCompaniesRouteChildren {
  CompetitorsCompaniesCompanyIdRoute: typeof CompetitorsCompaniesCompanyIdRoute
}

const CompetitorsCompaniesRouteChildren: CompetitorsCompaniesRouteChildren = {
  CompetitorsCompaniesCompanyIdRoute: CompetitorsCompaniesCompanyIdRoute,
}

const CompetitorsCompaniesRouteWithChildren =
  CompetitorsCompaniesRoute._addFileChildren(CompetitorsCompaniesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  SearchRoute: SearchRoute,
  ArticleIdRoute: ArticleIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  CompetitorsChangesRoute: CompetitorsChangesRoute,
  CompetitorsCompaniesRoute: CompetitorsCompaniesRouteWithChildren,
  CompetitorsInitiativesRoute: CompetitorsInitiativesRoute,
  CompetitorsOverviewRoute: CompetitorsOverviewRoute,
  CompetitorsTargetsRoute: CompetitorsTargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
